Add Makefile. getMax, getMin and isEqual methods
Zaboday/golang-course-tasks pull request #6
Opened 2020-11-22 19:44 UTC by Zaboday

**Added**

- Makefile with `run`, `build`, `lint` commands
- SliceManager's `getMax`, `getMin` methods
- Linked list benchmarks

2020-11-22 19:59 UTC, korjavin requested changes

2020-11-22 19:59 UTC, korjavin commented on task2/pkg/linkedlist/linkedlist_test.go
> +		r = list.Insert(i + x)
Всё таки мне не нравится что мы бенчмаркаем всегда на строго упорядоченных вставках.
Фактически же мы видим всегда один сценарий "последовательная вставка в середина/ конец списка".
Тут же никогда не будет вставки в начало списка. Или я недопонимаю?

2020-11-22 19:59 UTC, korjavin commented on task2/pkg/linkedlist/linkedlist_test.go
> +		list := makeList(size)
вот тут мне  кажется или надо исключать создание через stopTimer
или что то ещё придумывать.

2020-11-23 03:55 UTC, Zaboday commented on task2/pkg/linkedlist/linkedlist_test.go
> +		r = list.Insert(i + x)
Все верно.
Я добавлю и разделю бенчмарки на вставку в начало, в середину и в конец.

2020-11-23 03:55 UTC, Zaboday commented on task2/pkg/linkedlist/linkedlist_test.go
> +		list := makeList(size)
Сделаю stopTimer

2020-12-20 21:27 UTC, merged